### PR TITLE
hook into close

### PR DESCRIPTION
**Pull request by hackergrrl**
so that a server using this plugin can shut itself down

### CODE REVIEW

**Comment by dominictarr** [comment]
you don't actually need to clear the interval because we did `int.unref()` (which means it does not keep the process up) you are right the server does need to be closed though.

Also, can you give me some context what you need this for? there should probably be a test if you really need this

**Comment by hackergrrl** [comment]
@dominictarr I'm trying to write tests for an ssb client that can spin up its own server /w `secret-stack`. Right now the test process can't terminate because of this.

**Comment by dominictarr** [comment]
okay but can we have a small test in this repo?

**Comment by christianbundy** [comment]
Added a super simple test to demonstrate the behavior. On `master` the test fails, on this branch it passes.

:tada:

**Pull request merged**
